# =============================================================
# Tareas de configuración de la VM
# =============================================================

# -------------------------------------------------------------
# ACTUALIZAR RESPOSITORIOS
# -------------------------------------------------------------
- name: Actualizar repositorios del sistema
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

# -------------------------------------------------------------
# INSTALAR PODMAN
# -------------------------------------------------------------
- name: Instalar Podman
  apt:
    name: podman
    state: present  # "present" = instalar si no está instalado
  become: true

# -------------------------------------------------------------
# LOGIN EN EL ACR
# -------------------------------------------------------------
# La VM necesita autenticarse en el ACR para descargar imágenes
- name: Login en el ACR desde la VM
  containers.podman.podman_login:
    registry: "{{ acr_login_server }}"
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"

# -------------------------------------------------------------
# PULL DE IMAGEN NGINX DESDE EL ACR
# -------------------------------------------------------------
- name: Descargar imagen NGINX desde el ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/nginx"
    tag: casoPractico2
    state: present


# -------------------------------------------------------------
# ARRANCAR CONTENEDOR NGINX
# -------------------------------------------------------------
# Equivale a: podman run -d --name nginx -p 80:80 nginx
- name: Arrancar contenedor NGINX
  containers.podman.podman_container:
    name: nginx              # Nombre del contenedor
    image: "{{ acr_login_server }}/nginx:casoPractico2"
    state: started           # "started" = arrancar si no está corriendo
    ports:
      - "80:80"              # Puerto VM:Puerto contenedor
    restart_policy: always   # Reinicia el contenedor si se cae o reinicia la VM
  become: true               # Necesita privilegios para usar puerto <1024